import type { NativePlugin, PluginCategoryMeta } from './types';

export const PLUGIN_CATEGORIES: PluginCategoryMeta[] = [
  { key: 'ai',            label: 'AI / LLM',       icon: '🤖' },
  { key: 'blockchain',    label: 'Blockchain',      icon: '⛓️' },
  { key: 'communication', label: 'Comunicare',      icon: '💬' },
  { key: 'data',          label: 'Date & Analiză',  icon: '📊' },
  { key: 'devtools',      label: 'Dev Tools',       icon: '🛠️' },
  { key: 'productivity',  label: 'Productivitate',  icon: '⚡' },
];

export const NATIVE_PLUGINS: NativePlugin[] = [
  // ─── AI / LLM ───────────────────────────────────────────────
  {
    key: 'openai',
    name: 'OpenAI',
    icon: '🧠',
    description: 'GPT-4o, GPT-4-turbo, DALL·E 3, Whisper, Embeddings.',
    category: 'ai',
    capabilities: ['chat', 'completions', 'embeddings', 'image-gen', 'speech-to-text'],
    authType: 'apikey',
    isOpenClawSkill: true,
    docsUrl: 'https://platform.openai.com/docs',
    configFields: [
      { key: 'api_key', label: 'API Key', type: 'password', required: true, isSecret: true, placeholder: 'sk-...' },
      { key: 'model', label: 'Model implicit', type: 'select', required: false, isSecret: false, options: ['gpt-4o', 'gpt-4-turbo', 'gpt-3.5-turbo'] },
    ],
  },
  {
    key: 'openrouter',
    name: 'OpenRouter',
    icon: '🔀',
    description: 'Acces unificat la 200+ modele: Claude, Gemini, Llama, Mistral etc.',
    category: 'ai',
    capabilities: ['multi-model routing', 'chat', 'completions', 'fallback'],
    authType: 'apikey',
    isOpenClawSkill: true,
    docsUrl: 'https://openrouter.ai/docs',
    configFields: [
      { key: 'api_key', label: 'API Key', type: 'password', required: true, isSecret: true, placeholder: 'sk-or-...' },
      { key: 'default_model', label: 'Model implicit', type: 'text', required: false, isSecret: false, placeholder: 'anthropic/claude-3.5-sonnet' },
    ],
  },
  {
    key: 'anthropic',
    name: 'Anthropic Claude',
    icon: '🌀',
    description: 'Claude 3.5 Sonnet/Haiku — raționament avansat și context lung.',
    category: 'ai',
    capabilities: ['chat', 'analysis', 'code', 'long-context'],
    authType: 'apikey',
    docsUrl: 'https://docs.anthropic.com',
    configFields: [
      { key: 'api_key', label: 'API Key', type: 'password', required: true, isSecret: true, placeholder: 'sk-ant-...' },
    ],
  },
  {
    key: 'perplexity',
    name: 'Perplexity AI',
    icon: '🔍',
    description: 'Căutare web în timp real cu AI — sonar-pro și sonar-reasoning.',
    category: 'ai',
    capabilities: ['web search', 'real-time data', 'citations', 'research'],
    authType: 'apikey',
    isOpenClawSkill: true,
    docsUrl: 'https://docs.perplexity.ai',
    configFields: [
      { key: 'api_key', label: 'API Key', type: 'password', required: true, isSecret: true, placeholder: 'pplx-...' },
    ],
  },
  {
    key: 'elevenlabs',
    name: 'ElevenLabs',
    icon: '🎙️',
    description: 'Text-to-speech ultra-realist și clonare voce.',
    category: 'ai',
    capabilities: ['tts', 'voice cloning', 'audio generation'],
    authType: 'apikey',
    docsUrl: 'https://elevenlabs.io/docs',
    configFields: [
      { key: 'api_key', label: 'API Key', type: 'password', required: true, isSecret: true, placeholder: 'xi-...' },
    ],
  },

  // ─── BLOCKCHAIN ──────────────────────────────────────────────
  {
    key: 'multiversx_api',
    name: 'MultiversX API',
    icon: '⛓️',
    description: 'Date on-chain: conturi, tranzacții, NFT-uri, tokens ESDT. Free, no key.',
    category: 'blockchain',
    capabilities: ['balances', 'transactions', 'NFTs', 'tokens', 'validators'],
    authType: 'none',
    isOpenClawSkill: true,
    docsUrl: 'https://docs.multiversx.com/sdk-and-tools/rest-api/multiversx-api',
    configFields: [],
  },
  {
    key: 'multiversx_tx',
    name: 'MultiversX Send TX',
    icon: '💸',
    description: 'Trimite EGLD/ESDT sau interacționează cu smart contracts via xPortal.',
    category: 'blockchain',
    capabilities: ['send EGLD', 'send ESDT', 'smart contract calls', 'sign tx'],
    authType: 'none',
    isOpenClawSkill: true,
    docsUrl: 'https://docs.multiversx.com',
    configFields: [],
  },
  {
    key: 'coingecko',
    name: 'CoinGecko',
    icon: '🦎',
    description: 'Prețuri crypto live, capitalizare, volume — free tier 30 req/min.',
    category: 'blockchain',
    capabilities: ['price feed', 'market data', 'trending', 'portfolio'],
    authType: 'none',
    isOpenClawSkill: true,
    docsUrl: 'https://docs.coingecko.com',
    configFields: [],
  },
  {
    key: 'etherscan',
    name: 'Etherscan',
    icon: '🔷',
    description: 'Date on-chain Ethereum: adrese, tranzacții, ABI-uri contracte.',
    category: 'blockchain',
    capabilities: ['ETH balances', 'tx history', 'contract ABI', 'gas tracker'],
    authType: 'apikey',
    docsUrl: 'https://docs.etherscan.io',
    configFields: [
      { key: 'api_key', label: 'API Key', type: 'password', required: true, isSecret: true, placeholder: 'YourApiKeyToken' },
    ],
  },

  // ─── COMMUNICATION ───────────────────────────────────────────
  {
    key: 'telegram',
    name: 'Telegram Bot',
    icon: '✈️',
    description: 'Trimite mesaje, notificări și comenzi prin Telegram Bot API.',
    category: 'communication',
    capabilities: ['send message', 'receive commands', 'inline keyboards', 'files'],
    authType: 'apikey',
    isOpenClawSkill: true,
    docsUrl: 'https://core.telegram.org/bots/api',
    configFields: [
      { key: 'bot_token', label: 'Bot Token', type: 'password', required: true, isSecret: true, placeholder: '123456:ABC-...' },
      { key: 'chat_id', label: 'Chat ID implicit', type: 'text', required: false, isSecret: false, placeholder: '-100...' },
    ],
  },
  {
    key: 'discord',
    name: 'Discord',
    icon: '🎮',
    description: 'Webhook-uri și bot Discord pentru notificări și comenzi slash.',
    category: 'communication',
    capabilities: ['webhook messages', 'embeds', 'slash commands', 'channels'],
    authType: 'apikey',
    docsUrl: 'https://discord.com/developers/docs',
    configFields: [
      { key: 'webhook_url', label: 'Webhook URL', type: 'password', required: true, isSecret: true, placeholder: 'https://discord.com/api/webhooks/...' },
      { key: 'bot_token', label: 'Bot Token (opțional)', type: 'password', required: false, isSecret: true, placeholder: 'MT...' },
    ],
  },
  {
    key: 'slack',
    name: 'Slack',
    icon: '💼',
    description: 'Notificări, mesaje și workflow-uri în workspace Slack.',
    category: 'communication',
    capabilities: ['send message', 'blocks UI', 'channels', 'threads'],
    authType: 'oauth2',
    docsUrl: 'https://api.slack.com',
    configFields: [
      { key: 'bot_token', label: 'Bot Token', type: 'password', required: true, isSecret: true, placeholder: 'xoxb-...' },
      { key: 'channel', label: 'Canal implicit', type: 'text', required: false, isSecret: false, placeholder: '#general' },
    ],
  },

  // ─── DATA ────────────────────────────────────────────────────
  {
    key: 'serper',
    name: 'Serper (Google Search)',
    icon: '🌐',
    description: 'Google Search programatic: web, news, images — 2500 queries/lună free.',
    category: 'data',
    capabilities: ['web search', 'news search', 'image search', 'SERP data'],
    authType: 'apikey',
    isOpenClawSkill: true,
    docsUrl: 'https://serper.dev/docs',
    configFields: [
      { key: 'api_key', label: 'API Key', type: 'password', required: true, isSecret: true, placeholder: 'ser-...' },
    ],
  },
  {
    key: 'weatherapi',
    name: 'WeatherAPI',
    icon: '🌤️',
    description: 'Vreme curentă, forecast 14 zile, alertă meteo — free tier disponibil.',
    category: 'data',
    capabilities: ['current weather', 'forecast', 'alerts', 'history'],
    authType: 'apikey',
    isOpenClawSkill: true,
    docsUrl: 'https://www.weatherapi.com/docs',
    configFields: [
      { key: 'api_key', label: 'API Key', type: 'password', required: true, isSecret: true, placeholder: '...' },
    ],
  },
  {
    key: 'newsapi',
    name: 'NewsAPI',
    icon: '📰',
    description: 'Știri din 80.000 surse globale în timp real.',
    category: 'data',
    capabilities: ['headlines', 'search articles', 'sources', 'categories'],
    authType: 'apikey',
    docsUrl: 'https://newsapi.org/docs',
    configFields: [
      { key: 'api_key', label: 'API Key', type: 'password', required: true, isSecret: true, placeholder: '...' },
    ],
  },
  {
    key: 'supabase',
    name: 'Supabase',
    icon: '🗄️',
    description: 'Bază de date PostgreSQL, autentificare și stocare fișiere.',
    category: 'data',
    capabilities: ['database', 'auth', 'storage', 'realtime', 'edge functions'],
    authType: 'apikey',
    docsUrl: 'https://supabase.com/docs',
    configFields: [
      { key: 'url', label: 'Project URL', type: 'text', required: true, isSecret: false, placeholder: 'https://xxx.supabase.co' },
      { key: 'anon_key', label: 'Anon Key', type: 'password', required: true, isSecret: true, placeholder: 'eyJ...' },
      { key: 'service_key', label: 'Service Role Key (opțional)', type: 'password', required: false, isSecret: true, placeholder: 'eyJ...' },
    ],
  },

  // ─── DEVTOOLS ────────────────────────────────────────────────
  {
    key: 'github',
    name: 'GitHub',
    icon: '🐙',
    description: 'Issues, PRs, commits, repositories — acces complet la GitHub API.',
    category: 'devtools',
    capabilities: ['repos', 'issues', 'pull requests', 'commits', 'actions'],
    authType: 'apikey',
    isOpenClawSkill: true,
    docsUrl: 'https://docs.github.com/en/rest',
    configFields: [
      { key: 'token', label: 'Personal Access Token', type: 'password', required: true, isSecret: true, placeholder: 'ghp_...' },
      { key: 'default_repo', label: 'Repo implicit (owner/repo)', type: 'text', required: false, isSecret: false, placeholder: 'Gzeu/openclaw-hub' },
    ],
  },
  {
    key: 'vercel',
    name: 'Vercel',
    icon: '▲',
    description: 'Deploy-uri, logs, environment variables și domenii Vercel.',
    category: 'devtools',
    capabilities: ['deployments', 'logs', 'env vars', 'domains', 'projects'],
    authType: 'apikey',
    docsUrl: 'https://vercel.com/docs/rest-api',
    configFields: [
      { key: 'token', label: 'API Token', type: 'password', required: true, isSecret: true, placeholder: '...' },
      { key: 'team_id', label: 'Team ID (opțional)', type: 'text', required: false, isSecret: false, placeholder: 'team_...' },
    ],
  },
  {
    key: 'docker_hub',
    name: 'Docker Hub',
    icon: '🐳',
    description: 'Gestionare imagini Docker, tags și repository-uri.',
    category: 'devtools',
    capabilities: ['images', 'tags', 'push', 'pull', 'webhooks'],
    authType: 'apikey',
    docsUrl: 'https://docs.docker.com/docker-hub/api/latest',
    configFields: [
      { key: 'username', label: 'Username', type: 'text', required: true, isSecret: false, placeholder: 'username' },
      { key: 'token', label: 'Access Token', type: 'password', required: true, isSecret: true, placeholder: '...' },
    ],
  },

  // ─── PRODUCTIVITY ────────────────────────────────────────────
  {
    key: 'notion',
    name: 'Notion',
    icon: '📓',
    description: 'Citește și scrie pagini, baze de date și documente Notion.',
    category: 'productivity',
    capabilities: ['pages', 'databases', 'blocks', 'search', 'comments'],
    authType: 'apikey',
    isOpenClawSkill: true,
    docsUrl: 'https://developers.notion.com',
    configFields: [
      { key: 'token', label: 'Integration Token', type: 'password', required: true, isSecret: true, placeholder: 'secret_...' },
    ],
  },
  {
    key: 'google_calendar',
    name: 'Google Calendar',
    icon: '📅',
    description: 'Gestionare evenimente, invitații și disponibilitate.',
    category: 'productivity',
    capabilities: ['events', 'create', 'update', 'delete', 'availability'],
    authType: 'oauth2',
    docsUrl: 'https://developers.google.com/calendar',
    configFields: [
      { key: 'client_id', label: 'Client ID', type: 'text', required: true, isSecret: false, placeholder: '....apps.googleusercontent.com' },
      { key: 'client_secret', label: 'Client Secret', type: 'password', required: true, isSecret: true, placeholder: 'GOCSPX-...' },
    ],
  },
  {
    key: 'linear',
    name: 'Linear',
    icon: '📐',
    description: 'Issues, proiecte și sprint-uri Linear pentru echipe de engineering.',
    category: 'productivity',
    capabilities: ['issues', 'projects', 'cycles', 'roadmap', 'teams'],
    authType: 'apikey',
    docsUrl: 'https://developers.linear.app/docs',
    configFields: [
      { key: 'api_key', label: 'API Key', type: 'password', required: true, isSecret: true, placeholder: 'lin_api_...' },
    ],
  },
  {
    key: 'airtable',
    name: 'Airtable',
    icon: '🗂️',
    description: 'Citire și scriere în baze de date Airtable ca spreadsheet-uri.',
    category: 'productivity',
    capabilities: ['records', 'tables', 'views', 'filters', 'attachments'],
    authType: 'apikey',
    docsUrl: 'https://airtable.com/developers/web/api/introduction',
    configFields: [
      { key: 'api_key', label: 'Personal Access Token', type: 'password', required: true, isSecret: true, placeholder: 'pat...' },
      { key: 'base_id', label: 'Base ID', type: 'text', required: false, isSecret: false, placeholder: 'app...' },
    ],
  },
];

/** Look up a single plugin definition by its key. */
export function getPluginByKey(key: string): NativePlugin | undefined {
  return NATIVE_PLUGINS.find((p) => p.key === key);
}
