import type { NativePlugin, PluginCategoryMeta } from './types';

export const PLUGIN_CATEGORIES: PluginCategoryMeta[] = [
  { key: 'ai',             label: 'AI & LLM',       icon: '🤖' },
  { key: 'blockchain',     label: 'Blockchain',      icon: '⛓️' },
  { key: 'communication',  label: 'Comunicare',      icon: '💬' },
  { key: 'developer',      label: 'Developer',       icon: '👨‍💻' },
  { key: 'data',           label: 'Date & Search',   icon: '📊' },
  { key: 'productivity',   label: 'Productivitate',  icon: '⚡' },
  { key: 'social',         label: 'Social',          icon: '🌐' },
  { key: 'finance',        label: 'Finance',         icon: '💰' },
  { key: 'infrastructure', label: 'Infrastructură',  icon: '🏗️' },
  { key: 'media',          label: 'Media',           icon: '🎬' },
  { key: 'security',       label: 'Securitate',      icon: '🔐' },
];

export const NATIVE_PLUGINS: NativePlugin[] = [
  // ─── AI & LLM ───────────────────────────────────────────────────────────
  {
    key: 'openrouter',
    name: 'OpenRouter',
    icon: '🔀',
    description: 'Acces la 200+ modele AI (GPT-4o, Claude, Gemini, Llama, DeepSeek) cu un singur API key.',
    category: 'ai',
    authType: 'apikey',
    capabilities: ['LLM completions', 'Streaming', 'Tool calling', 'Model routing', 'Fallback'],
    configFields: [
      { key: 'apiKey', label: 'OpenRouter API Key', type: 'password', required: true, isSecret: true, placeholder: 'sk-or-...', helpText: 'Obține de la openrouter.ai' },
      { key: 'defaultModel', label: 'Model implicit', type: 'select', required: false, isSecret: false, options: ['openai/gpt-4o', 'anthropic/claude-3.5-sonnet', 'google/gemini-2.0-flash-001', 'deepseek/deepseek-r1', 'meta-llama/llama-3.3-70b-instruct', 'mistralai/mistral-large'], placeholder: 'openai/gpt-4o' },
    ],
    docsUrl: 'https://openrouter.ai/docs',
    isOpenClawSkill: true, skillSlug: 'openrouter-provider',
    version: '1.0.0',
  },
  {
    key: 'groq',
    name: 'Groq',
    icon: '⚡',
    description: 'Inferență LLM ultra-rapidă (Llama3, Mixtral, Gemma). Ideal pentru agenți care necesită viteza.',
    category: 'ai',
    authType: 'apikey',
    capabilities: ['Ultra-fast LLM', 'Llama3', 'Mixtral', 'Low latency'],
    configFields: [
      { key: 'apiKey', label: 'Groq API Key', type: 'password', required: true, isSecret: true, placeholder: 'gsk_...' },
    ],
    docsUrl: 'https://console.groq.com/docs',
    isOpenClawSkill: true, skillSlug: 'groq-provider',
    version: '1.0.0',
  },
  {
    key: 'anthropic',
    name: 'Anthropic Claude',
    icon: '🧠',
    description: 'Claude 3.5 Sonnet, Claude Opus 4 — modele AI de top pentru raționament și cod.',
    category: 'ai',
    authType: 'apikey',
    capabilities: ['Reasoning', 'Code', 'Long context', 'Vision', 'Tool use'],
    configFields: [
      { key: 'apiKey', label: 'Anthropic API Key', type: 'password', required: true, isSecret: true, placeholder: 'sk-ant-...' },
    ],
    docsUrl: 'https://docs.anthropic.com',
    isOpenClawSkill: false,
    version: '1.0.0',
  },
  {
    key: 'openai',
    name: 'OpenAI',
    icon: '🌀',
    description: 'GPT-4o, o3-mini, DALL-E, Whisper, Embeddings — ecosistemul complet OpenAI.',
    category: 'ai',
    authType: 'apikey',
    capabilities: ['GPT-4o', 'Image generation', 'STT/TTS', 'Embeddings', 'o3-mini reasoning'],
    configFields: [
      { key: 'apiKey', label: 'OpenAI API Key', type: 'password', required: true, isSecret: true, placeholder: 'sk-...' },
    ],
    docsUrl: 'https://platform.openai.com/docs',
    isOpenClawSkill: false,
    version: '1.0.0',
  },
  {
    key: 'gemini',
    name: 'Google Gemini',
    icon: '💎',
    description: 'Gemini 2.0 Flash, Pro, Ultra — modele Google cu context lung și multimodal.',
    category: 'ai',
    authType: 'apikey',
    capabilities: ['Multimodal', 'Long context (2M tokens)', 'Code', 'Grounding'],
    configFields: [
      { key: 'apiKey', label: 'Google AI API Key', type: 'password', required: true, isSecret: true, placeholder: 'AIza...' },
    ],
    docsUrl: 'https://ai.google.dev/docs',
    isOpenClawSkill: true, skillSlug: 'gemini-provider',
    version: '1.0.0',
  },
  {
    key: 'ollama',
    name: 'Ollama (Local LLM)',
    icon: '🦙',
    description: 'Rulează modele AI local (Llama3, Mistral, Phi, CodeLlama) fără cloud.',
    category: 'ai',
    authType: 'none',
    capabilities: ['Local inference', 'Privacy', 'No cost', 'Custom models'],
    configFields: [
      { key: 'baseUrl', label: 'Ollama Base URL', type: 'url', required: true, isSecret: false, placeholder: 'http://localhost:11434' },
      { key: 'defaultModel', label: 'Model implicit', type: 'text', required: false, isSecret: false, placeholder: 'llama3.2' },
    ],
    docsUrl: 'https://ollama.ai',
    isOpenClawSkill: true, skillSlug: 'ollama-provider',
    version: '1.0.0',
  },
  {
    key: 'perplexity-ai',
    name: 'Perplexity AI',
    icon: '🔍',
    description: 'LLM cu search integrat și răspunsuri citate în timp real.',
    category: 'ai',
    authType: 'apikey',
    capabilities: ['Search-augmented LLM', 'Real-time info', 'Citations', 'Sonar models'],
    configFields: [
      { key: 'apiKey', label: 'Perplexity API Key', type: 'password', required: true, isSecret: true, placeholder: 'pplx-...' },
    ],
    docsUrl: 'https://docs.perplexity.ai',
    isOpenClawSkill: false,
    version: '1.0.0',
  },
  {
    key: 'mistral',
    name: 'Mistral AI',
    icon: '🌪️',
    description: 'Mistral Large, Codestral, Mixtral — modele open-weight de top europene.',
    category: 'ai',
    authType: 'apikey',
    capabilities: ['Efficient LLM', 'Code (Codestral)', 'Mixture of Experts'],
    configFields: [
      { key: 'apiKey', label: 'Mistral API Key', type: 'password', required: true, isSecret: true, placeholder: 'api-...' },
    ],
    docsUrl: 'https://docs.mistral.ai',
    isOpenClawSkill: false,
    version: '1.0.0',
  },
  {
    key: 'together-ai',
    name: 'Together AI',
    icon: '🤝',
    description: 'Inferentă open-source rapidă și ieftină pentru modele ca Llama, Qwen, DeepSeek.',
    category: 'ai',
    authType: 'apikey',
    capabilities: ['Open-source models', 'Fine-tuning', 'Batch inference'],
    configFields: [
      { key: 'apiKey', label: 'Together AI API Key', type: 'password', required: true, isSecret: true, placeholder: '' },
    ],
    docsUrl: 'https://docs.together.ai',
    isOpenClawSkill: false,
    version: '1.0.0',
  },

  // ─── BLOCKCHAIN ────────────────────────────────────────────────────────
  {
    key: 'multiversx',
    name: 'MultiversX',
    icon: '⚡',
    description: 'Balance, tranzacții, tokens, NFTs, smart contracts pe MultiversX mainnet.',
    category: 'blockchain',
    authType: 'none',
    capabilities: ['EGLD balance', 'ESDT tokens', 'NFTs', 'Transactions', 'Smart contracts'],
    configFields: [],
    docsUrl: 'https://docs.multiversx.com',
    isOpenClawSkill: true, skillSlug: 'mvx-tools',
    version: '1.0.0',
  },
  {
    key: 'coingecko',
    name: 'CoinGecko',
    icon: '🦎',
    description: 'Prețuri crypto, market cap, volume pentru 10k+ tokeni. API gratuit disponibil.',
    category: 'blockchain',
    authType: 'none',
    capabilities: ['Price feeds', 'Market data', 'Historical data', '10k+ tokens'],
    configFields: [
      { key: 'apiKey', label: 'CoinGecko API Key (opțional, Pro)', type: 'password', required: false, isSecret: true, placeholder: 'CG-...' },
    ],
    docsUrl: 'https://www.coingecko.com/api/documentation',
    isOpenClawSkill: true, skillSlug: 'price-feed',
    version: '1.0.0',
  },
  {
    key: 'binance',
    name: 'Binance',
    icon: '🟡',
    description: 'Prețuri live, order book, account info și trading pe Binance.',
    category: 'blockchain',
    authType: 'apikey',
    capabilities: ['Spot trading', 'Price streams', 'Account balance', 'Order management'],
    configFields: [
      { key: 'apiKey', label: 'Binance API Key', type: 'password', required: true, isSecret: true, placeholder: '' },
      { key: 'secretKey', label: 'Binance Secret Key', type: 'password', required: true, isSecret: true, placeholder: '' },
    ],
    docsUrl: 'https://binance-docs.github.io/apidocs/',
    isOpenClawSkill: false,
    version: '1.0.0',
  },
  {
    key: 'etherscan',
    name: 'Etherscan',
    icon: '🔷',
    description: 'Blockchain explorer pentru Ethereum — tranzacții, contracte, balante.',
    category: 'blockchain',
    authType: 'apikey',
    capabilities: ['ETH balance', 'Transactions', 'Contract ABI', 'Token transfers'],
    configFields: [
      { key: 'apiKey', label: 'Etherscan API Key', type: 'password', required: true, isSecret: true, placeholder: '' },
    ],
    docsUrl: 'https://docs.etherscan.io',
    isOpenClawSkill: false,
    version: '1.0.0',
  },

  // ─── COMMUNICATION ────────────────────────────────────────────────────
  {
    key: 'telegram',
    name: 'Telegram Bot',
    icon: '✈️',
    description: 'Trimite mesaje, notificări și interacționează cu utilizatorii prin bot Telegram.',
    category: 'communication',
    authType: 'apikey',
    capabilities: ['Send messages', 'Receive updates', 'Inline keyboards', 'File upload', 'Bot commands'],
    configFields: [
      { key: 'botToken', label: 'Telegram Bot Token', type: 'password', required: true, isSecret: true, placeholder: '123456:ABC-...', helpText: 'Obține de la @BotFather pe Telegram' },
      { key: 'chatId', label: 'Chat ID implicit (opțional)', type: 'text', required: false, isSecret: false, placeholder: '-100...' },
    ],
    docsUrl: 'https://core.telegram.org/bots/api',
    isOpenClawSkill: true, skillSlug: 'telegram-bot',
    version: '1.0.0',
  },
  {
    key: 'discord',
    name: 'Discord',
    icon: '🎮',
    description: 'Bot Discord pentru notificări, comenzi și monitorizare servere.',
    category: 'communication',
    authType: 'apikey',
    capabilities: ['Send messages', 'Webhooks', 'Bot commands', 'Server monitoring'],
    configFields: [
      { key: 'botToken', label: 'Discord Bot Token', type: 'password', required: true, isSecret: true, placeholder: '' },
      { key: 'guildId', label: 'Server (Guild) ID', type: 'text', required: false, isSecret: false, placeholder: '' },
      { key: 'channelId', label: 'Channel ID implicit', type: 'text', required: false, isSecret: false, placeholder: '' },
    ],
    docsUrl: 'https://discord.com/developers/docs',
    isOpenClawSkill: false,
    version: '1.0.0',
  },
  {
    key: 'slack',
    name: 'Slack',
    icon: '💼',
    description: 'Integrare Slack pentru notificări și automatizări în workspace-ul echipei.',
    category: 'communication',
    authType: 'oauth2',
    capabilities: ['Send messages', 'Create channels', 'Webhooks', 'Thread replies', 'File sharing'],
    configFields: [
      { key: 'botToken', label: 'Slack Bot Token', type: 'password', required: true, isSecret: true, placeholder: 'xoxb-...' },
      { key: 'channelId', label: 'Channel ID implicit', type: 'text', required: false, isSecret: false, placeholder: 'C0...' },
    ],
    docsUrl: 'https://api.slack.com',
    isOpenClawSkill: false,
    version: '1.0.0',
  },
  {
    key: 'email-smtp',
    name: 'Email (SMTP)',
    icon: '📧',
    description: 'Trimite emailuri prin orice provider SMTP (Gmail, SendGrid, Mailgun, etc.).',
    category: 'communication',
    authType: 'apikey',
    capabilities: ['Send emails', 'HTML/plain text', 'Attachments', 'Custom from'],
    configFields: [
      { key: 'host', label: 'SMTP Host', type: 'text', required: true, isSecret: false, placeholder: 'smtp.gmail.com' },
      { key: 'port', label: 'Port', type: 'text', required: true, isSecret: false, placeholder: '587' },
      { key: 'user', label: 'Username/Email', type: 'email', required: true, isSecret: false, placeholder: '' },
      { key: 'password', label: 'Password/App Password', type: 'password', required: true, isSecret: true, placeholder: '' },
    ],
    docsUrl: 'https://nodemailer.com',
    isOpenClawSkill: false,
    version: '1.0.0',
  },
  {
    key: 'twilio',
    name: 'Twilio',
    icon: '📱',
    description: 'SMS, WhatsApp și apeluri telefonice programabile prin Twilio.',
    category: 'communication',
    authType: 'apikey',
    capabilities: ['Send SMS', 'WhatsApp', 'Voice calls', 'Verify OTP'],
    configFields: [
      { key: 'accountSid', label: 'Account SID', type: 'text', required: true, isSecret: false, placeholder: 'AC...' },
      { key: 'authToken', label: 'Auth Token', type: 'password', required: true, isSecret: true, placeholder: '' },
      { key: 'fromNumber', label: 'Număr expeditor', type: 'text', required: true, isSecret: false, placeholder: '+1...' },
    ],
    docsUrl: 'https://www.twilio.com/docs',
    isOpenClawSkill: false,
    version: '1.0.0',
  },

  // ─── DEVELOPER ────────────────────────────────────────────────────────
  {
    key: 'github',
    name: 'GitHub',
    icon: '🐙',
    description: 'Gestionează repository-uri, issues, PRs, commits și workflows GitHub Actions.',
    category: 'developer',
    authType: 'apikey',
    capabilities: ['Repos', 'Issues', 'PRs', 'Commits', 'Actions', 'Gists', 'Search code'],
    configFields: [
      { key: 'token', label: 'GitHub Personal Access Token', type: 'password', required: true, isSecret: true, placeholder: 'ghp_...', helpText: 'github.com/settings/tokens → scopes: repo, read:user' },
      { key: 'defaultOwner', label: 'Owner/Org implicit', type: 'text', required: false, isSecret: false, placeholder: 'username sau org' },
    ],
    docsUrl: 'https://docs.github.com/rest',
    isOpenClawSkill: true, skillSlug: 'github-tools',
    version: '1.0.0',
  },
  {
    key: 'gitlab',
    name: 'GitLab',
    icon: '🦊',
    description: 'API GitLab pentru repo-uri, merge requests, pipelines CI/CD.',
    category: 'developer',
    authType: 'apikey',
    capabilities: ['Repos', 'MRs', 'Pipelines', 'Issues', 'Registries'],
    configFields: [
      { key: 'token', label: 'GitLab Personal Access Token', type: 'password', required: true, isSecret: true, placeholder: 'glpat-...' },
      { key: 'instanceUrl', label: 'GitLab URL', type: 'url', required: false, isSecret: false, placeholder: 'https://gitlab.com' },
    ],
    docsUrl: 'https://docs.gitlab.com/ee/api/',
    isOpenClawSkill: false,
    version: '1.0.0',
  },
  {
    key: 'e2b',
    name: 'E2B Code Sandbox',
    icon: '🧪',
    description: 'Execuție cod în sandbox-uri securizate cloud (Python, JS, Bash).',
    category: 'developer',
    authType: 'apikey',
    capabilities: ['Run Python', 'Run JS', 'Run bash', 'File system', 'Secure sandbox'],
    configFields: [
      { key: 'apiKey', label: 'E2B API Key', type: 'password', required: true, isSecret: true, placeholder: 'e2b_...' },
    ],
    docsUrl: 'https://e2b.dev/docs',
    isOpenClawSkill: true, skillSlug: 'code-execute',
    version: '1.0.0',
  },
  {
    key: 'supabase',
    name: 'Supabase',
    icon: '⚡',
    description: 'Database Postgres, Auth, Storage și Realtime via Supabase.',
    category: 'developer',
    authType: 'apikey',
    capabilities: ['Postgres queries', 'Auth', 'File storage', 'Realtime', 'Edge functions'],
    configFields: [
      { key: 'url', label: 'Supabase Project URL', type: 'url', required: true, isSecret: false, placeholder: 'https://xxx.supabase.co' },
      { key: 'anonKey', label: 'Anon Key', type: 'password', required: true, isSecret: true, placeholder: 'eyJ...' },
      { key: 'serviceKey', label: 'Service Role Key (opțional)', type: 'password', required: false, isSecret: true, placeholder: 'eyJ...' },
    ],
    docsUrl: 'https://supabase.com/docs',
    isOpenClawSkill: false,
    version: '1.0.0',
  },
  {
    key: 'vercel',
    name: 'Vercel',
    icon: '▲',
    description: 'Deploy, logs, env vars și domini Vercel prin API.',
    category: 'developer',
    authType: 'apikey',
    capabilities: ['Deploy projects', 'Env vars', 'Domains', 'Logs', 'Functions'],
    configFields: [
      { key: 'token', label: 'Vercel Access Token', type: 'password', required: true, isSecret: true, placeholder: '' },
      { key: 'teamId', label: 'Team ID (opțional)', type: 'text', required: false, isSecret: false, placeholder: 'team_...' },
    ],
    docsUrl: 'https://vercel.com/docs/rest-api',
    isOpenClawSkill: false,
    version: '1.0.0',
  },
  {
    key: 'linear',
    name: 'Linear',
    icon: '📐',
    description: 'Project management și issue tracking pentru echipe de dev.',
    category: 'developer',
    authType: 'apikey',
    capabilities: ['Issues', 'Projects', 'Cycles', 'Teams', 'Roadmaps'],
    configFields: [
      { key: 'apiKey', label: 'Linear API Key', type: 'password', required: true, isSecret: true, placeholder: 'lin_api_...' },
    ],
    docsUrl: 'https://developers.linear.app/docs',
    isOpenClawSkill: false,
    version: '1.0.0',
  },

  // ─── DATA & SEARCH ─────────────────────────────────────────────────────
  {
    key: 'tavily',
    name: 'Tavily Search',
    icon: '🔎',
    description: 'Search engine optimizat pentru AI — context relevant, surse verificate.',
    category: 'data',
    authType: 'apikey',
    capabilities: ['Web search', 'AI-optimized results', 'Context extraction', 'News search'],
    configFields: [
      { key: 'apiKey', label: 'Tavily API Key', type: 'password', required: true, isSecret: true, placeholder: 'tvly-...' },
    ],
    docsUrl: 'https://docs.tavily.com',
    isOpenClawSkill: true, skillSlug: 'web-search',
    version: '1.0.0',
  },
  {
    key: 'brave-search',
    name: 'Brave Search',
    icon: '🦁',
    description: 'Search web independent de Google, cu API dedicat pentru AI agents.',
    category: 'data',
    authType: 'apikey',
    capabilities: ['Web search', 'News', 'Independent index', 'No tracking'],
    configFields: [
      { key: 'apiKey', label: 'Brave Search API Key', type: 'password', required: true, isSecret: true, placeholder: 'BSA...' },
    ],
    docsUrl: 'https://brave.com/search/api/',
    isOpenClawSkill: true, skillSlug: 'brave-search',
    version: '1.0.0',
  },
  {
    key: 'jina-reader',
    name: 'Jina Reader',
    icon: '📖',
    description: 'Extrage conținut clean din orice URL pentru context LLM (r.jina.ai).',
    category: 'data',
    authType: 'none',
    capabilities: ['Web scraping', 'Content extraction', 'Markdown output', 'PDF support'],
    configFields: [
      { key: 'apiKey', label: 'Jina API Key (opțional)', type: 'password', required: false, isSecret: true, placeholder: 'jina_...' },
    ],
    docsUrl: 'https://jina.ai/reader/',
    isOpenClawSkill: true, skillSlug: 'scrape-url',
    version: '1.0.0',
  },
  {
    key: 'firecrawl',
    name: 'Firecrawl',
    icon: '🔥',
    description: 'Scraping avansat pentru site-uri dinamice — crawl, map, batch extract.',
    category: 'data',
    authType: 'apikey',
    capabilities: ['Dynamic scraping', 'Full-site crawl', 'Structured extraction', 'JS rendering'],
    configFields: [
      { key: 'apiKey', label: 'Firecrawl API Key', type: 'password', required: true, isSecret: true, placeholder: 'fc-...' },
    ],
    docsUrl: 'https://docs.firecrawl.dev',
    isOpenClawSkill: true, skillSlug: 'extract-content',
    version: '1.0.0',
  },
  {
    key: 'wikipedia',
    name: 'Wikipedia',
    icon: '📚',
    description: 'Search și extrage articole Wikipedia fără API key.',
    category: 'data',
    authType: 'none',
    capabilities: ['Article search', 'Full content', 'Multilingual', 'Free'],
    configFields: [],
    docsUrl: 'https://www.mediawiki.org/wiki/API:Main_page',
    isOpenClawSkill: true, skillSlug: 'wiki-search',
    version: '1.0.0',
  },
  {
    key: 'open-meteo',
    name: 'Open-Meteo (Weather)',
    icon: '🌤️',
    description: 'Date meteo precise pentru orice locație — forecast, istoric, curent. 100% gratuit.',
    category: 'data',
    authType: 'none',
    capabilities: ['Current weather', '16-day forecast', 'Historical data', 'Air quality'],
    configFields: [],
    docsUrl: 'https://open-meteo.com/en/docs',
    isOpenClawSkill: true, skillSlug: 'weather',
    version: '1.0.0',
  },
  {
    key: 'serper',
    name: 'Serper (Google Search)',
    icon: '🔍',
    description: 'Rezultate Google Search prin API — web, news, images, shopping.',
    category: 'data',
    authType: 'apikey',
    capabilities: ['Google search', 'News', 'Images', 'Shopping', 'Maps'],
    configFields: [
      { key: 'apiKey', label: 'Serper API Key', type: 'password', required: true, isSecret: true, placeholder: '' },
    ],
    docsUrl: 'https://serper.dev/api-reference',
    isOpenClawSkill: false,
    version: '1.0.0',
  },

  // ─── PRODUCTIVITY ────────────────────────────────────────────────────
  {
    key: 'notion',
    name: 'Notion',
    icon: '📝',
    description: 'Citește, scrie și organizează în Notion databases, pages și documents.',
    category: 'productivity',
    authType: 'apikey',
    capabilities: ['Read/write pages', 'Database queries', 'Block creation', 'Search'],
    configFields: [
      { key: 'integrationToken', label: 'Notion Integration Token', type: 'password', required: true, isSecret: true, placeholder: 'secret_...' },
    ],
    docsUrl: 'https://developers.notion.com',
    isOpenClawSkill: false,
    version: '1.0.0',
  },
  {
    key: 'google-calendar',
    name: 'Google Calendar',
    icon: '📅',
    description: 'Creează, citește și modifică evenimente în Google Calendar.',
    category: 'productivity',
    authType: 'oauth2',
    capabilities: ['Read events', 'Create events', 'Update/delete', 'Multiple calendars'],
    configFields: [
      { key: 'clientId', label: 'Google Client ID', type: 'text', required: true, isSecret: false, placeholder: '' },
      { key: 'clientSecret', label: 'Google Client Secret', type: 'password', required: true, isSecret: true, placeholder: '' },
      { key: 'refreshToken', label: 'Refresh Token', type: 'password', required: true, isSecret: true, placeholder: '' },
    ],
    docsUrl: 'https://developers.google.com/calendar',
    isOpenClawSkill: false,
    version: '1.0.0',
  },
  {
    key: 'airtable',
    name: 'Airtable',
    icon: '🗃️',
    description: 'Baze de date spreadsheet-like — citire, scriere, filtrare înregistrări.',
    category: 'productivity',
    authType: 'apikey',
    capabilities: ['Read records', 'Create/update records', 'Filter/sort', 'Multiple tables'],
    configFields: [
      { key: 'apiKey', label: 'Airtable Personal Access Token', type: 'password', required: true, isSecret: true, placeholder: 'pat...' },
      { key: 'baseId', label: 'Base ID implicit', type: 'text', required: false, isSecret: false, placeholder: 'app...' },
    ],
    docsUrl: 'https://airtable.com/developers/web/api/introduction',
    isOpenClawSkill: false,
    version: '1.0.0',
  },

  // ─── SOCIAL ───────────────────────────────────────────────────────────
  {
    key: 'twitter-x',
    name: 'Twitter / X',
    icon: '𝕏',
    description: 'Post tweets, citește timeline și monitorizează mențiuni pe Twitter/X.',
    category: 'social',
    authType: 'apikey',
    capabilities: ['Post tweets', 'Read timeline', 'Search tweets', 'Mentions', 'DMs'],
    configFields: [
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, isSecret: true, placeholder: '' },
      { key: 'apiSecret', label: 'API Secret', type: 'password', required: true, isSecret: true, placeholder: '' },
      { key: 'accessToken', label: 'Access Token', type: 'password', required: true, isSecret: true, placeholder: '' },
      { key: 'accessTokenSecret', label: 'Access Token Secret', type: 'password', required: true, isSecret: true, placeholder: '' },
    ],
    docsUrl: 'https://developer.twitter.com/en/docs',
    isOpenClawSkill: false,
    version: '1.0.0',
  },
  {
    key: 'reddit',
    name: 'Reddit',
    icon: '🤖',
    description: 'Citește și postează pe Reddit — subreddits, posts, comments, user feeds.',
    category: 'social',
    authType: 'apikey',
    capabilities: ['Read posts', 'Post/comment', 'Search', 'Monitor subreddits'],
    configFields: [
      { key: 'clientId', label: 'Client ID', type: 'text', required: true, isSecret: false, placeholder: '' },
      { key: 'clientSecret', label: 'Client Secret', type: 'password', required: true, isSecret: true, placeholder: '' },
      { key: 'username', label: 'Username Reddit', type: 'text', required: true, isSecret: false, placeholder: '' },
      { key: 'password', label: 'Password Reddit', type: 'password', required: true, isSecret: true, placeholder: '' },
    ],
    docsUrl: 'https://www.reddit.com/dev/api',
    isOpenClawSkill: false,
    version: '1.0.0',
  },

  // ─── FINANCE ────────────────────────────────────────────────────────
  {
    key: 'stripe',
    name: 'Stripe',
    icon: '💳',
    description: 'Procesare plăți, subscriptions, invoices și dashboard financiar.',
    category: 'finance',
    authType: 'apikey',
    capabilities: ['Payments', 'Subscriptions', 'Invoices', 'Customers', 'Refunds'],
    configFields: [
      { key: 'secretKey', label: 'Stripe Secret Key', type: 'password', required: true, isSecret: true, placeholder: 'sk_live_...' },
      { key: 'webhookSecret', label: 'Webhook Secret (opțional)', type: 'password', required: false, isSecret: true, placeholder: 'whsec_...' },
    ],
    docsUrl: 'https://stripe.com/docs/api',
    isOpenClawSkill: false,
    version: '1.0.0',
  },
  {
    key: 'alpha-vantage',
    name: 'Alpha Vantage (Stocks)',
    icon: '📈',
    description: 'Date piețe financiare — acțiuni, forex, crypto, indicatori tehnici.',
    category: 'finance',
    authType: 'apikey',
    capabilities: ['Stock prices', 'Forex', 'Technical indicators', 'Historical data', 'Earnings'],
    configFields: [
      { key: 'apiKey', label: 'Alpha Vantage API Key', type: 'password', required: true, isSecret: true, placeholder: '' },
    ],
    docsUrl: 'https://www.alphavantage.co/documentation/',
    isOpenClawSkill: false,
    version: '1.0.0',
  },

  // ─── INFRASTRUCTURE ──────────────────────────────────────────────────
  {
    key: 'cloudflare',
    name: 'Cloudflare',
    icon: '☁️',
    description: 'DNS, cache, Workers, R2 storage și security prin Cloudflare API.',
    category: 'infrastructure',
    authType: 'apikey',
    capabilities: ['DNS management', 'Cache purge', 'Workers deploy', 'R2 storage', 'Security rules'],
    configFields: [
      { key: 'apiToken', label: 'Cloudflare API Token', type: 'password', required: true, isSecret: true, placeholder: '' },
      { key: 'accountId', label: 'Account ID', type: 'text', required: true, isSecret: false, placeholder: '' },
    ],
    docsUrl: 'https://developers.cloudflare.com/api/',
    isOpenClawSkill: false,
    version: '1.0.0',
  },
  {
    key: 'aws',
    name: 'Amazon Web Services',
    icon: '☁️',
    description: 'S3, Lambda, EC2, SES și alte servicii AWS prin SDK.',
    category: 'infrastructure',
    authType: 'apikey',
    capabilities: ['S3 storage', 'Lambda functions', 'EC2', 'SES email', 'DynamoDB'],
    configFields: [
      { key: 'accessKeyId', label: 'AWS Access Key ID', type: 'text', required: true, isSecret: false, placeholder: 'AKIA...' },
      { key: 'secretAccessKey', label: 'AWS Secret Access Key', type: 'password', required: true, isSecret: true, placeholder: '' },
      { key: 'region', label: 'Region', type: 'text', required: true, isSecret: false, placeholder: 'eu-west-1' },
    ],
    docsUrl: 'https://docs.aws.amazon.com',
    isOpenClawSkill: false,
    version: '1.0.0',
  },
  {
    key: 'docker-hub',
    name: 'Docker Hub',
    icon: '🐳',
    description: 'Caută și gestionează imagini Docker din Hub.',
    category: 'infrastructure',
    authType: 'apikey',
    capabilities: ['Search images', 'Pull/push', 'Tags', 'Repositories'],
    configFields: [
      { key: 'username', label: 'Docker Hub Username', type: 'text', required: true, isSecret: false, placeholder: '' },
      { key: 'password', label: 'Docker Hub Password/PAT', type: 'password', required: true, isSecret: true, placeholder: '' },
    ],
    docsUrl: 'https://docs.docker.com/docker-hub/api/latest/',
    isOpenClawSkill: false,
    version: '1.0.0',
  },

  // ─── MEDIA ────────────────────────────────────────────────────────────
  {
    key: 'youtube',
    name: 'YouTube',
    icon: '▶️',
    description: 'Caută video-uri, obține transcript-uri și statistici canale YouTube.',
    category: 'media',
    authType: 'apikey',
    capabilities: ['Video search', 'Transcripts', 'Channel stats', 'Comments'],
    configFields: [
      { key: 'apiKey', label: 'YouTube Data API v3 Key', type: 'password', required: true, isSecret: true, placeholder: 'AIza...' },
    ],
    docsUrl: 'https://developers.google.com/youtube/v3',
    isOpenClawSkill: false,
    version: '1.0.0',
  },
  {
    key: 'spotify',
    name: 'Spotify',
    icon: '🎵',
    description: 'Date muzică, playlist-uri, artisti și tracking redare prin Spotify API.',
    category: 'media',
    authType: 'oauth2',
    capabilities: ['Search tracks', 'Playlists', 'Artist data', 'Playback control'],
    configFields: [
      { key: 'clientId', label: 'Spotify Client ID', type: 'text', required: true, isSecret: false, placeholder: '' },
      { key: 'clientSecret', label: 'Spotify Client Secret', type: 'password', required: true, isSecret: true, placeholder: '' },
    ],
    docsUrl: 'https://developer.spotify.com/documentation/web-api',
    isOpenClawSkill: false,
    version: '1.0.0',
  },

  // ─── SECURITY ────────────────────────────────────────────────────────
  {
    key: 'shodan',
    name: 'Shodan',
    icon: '👁️',
    description: 'Caută dispozitive conectate la internet, porturi deschise și vulnerabilități.',
    category: 'security',
    authType: 'apikey',
    capabilities: ['Host lookup', 'Port scan results', 'CVE search', 'Network intel'],
    configFields: [
      { key: 'apiKey', label: 'Shodan API Key', type: 'password', required: true, isSecret: true, placeholder: '' },
    ],
    docsUrl: 'https://developer.shodan.io',
    isOpenClawSkill: false,
    version: '1.0.0',
  },
  {
    key: 'virustotal',
    name: 'VirusTotal',
    icon: '🦠',
    description: 'Analizează fișiere, URL-uri și hash-uri pentru malware cu 70+ antivirus engines.',
    category: 'security',
    authType: 'apikey',
    capabilities: ['File scan', 'URL scan', 'Hash lookup', 'Domain reputation'],
    configFields: [
      { key: 'apiKey', label: 'VirusTotal API Key', type: 'password', required: true, isSecret: true, placeholder: '' },
    ],
    docsUrl: 'https://developers.virustotal.com/reference',
    isOpenClawSkill: false,
    version: '1.0.0',
  },
];
